test optimize precise-output
set opt_level=speed
target x86_64

function %f(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 2
  v2 = imul v0, v1
  v3 = imul v2, v1
  v4 = imul v3, v1
  v5 = imul v4, v1
  v6 = imul v5, v1
  v7 = imul v6, v1
  v8 = imul v7, v1
  v9 = imul v8, v1
  v10 = imul v9, v1
  v11 = imul v10, v1
  return v11
}

; function %f(i32) -> i32 fast {
; block0(v0: i32):
;     v12 = iadd v0, v0
;     v42 = iadd v12, v12
;     v74 = iadd v42, v42
;     v1 = iconst.i32 2
;     v113 = ishl v74, v1  ; v1 = 2
;     v48 = iconst.i32 8
;     v258 = imul v113, v48  ; v48 = 8
;     v22 = iconst.i32 4
;     v362 = imul v258, v22  ; v22 = 4
;     return v362
; }

